name: Test

on:
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential 

    - name: Setup project
      run: cmake .

    - name: Run tests
      run: make -j4 run_tests 

